# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8af6453bc1d223eaed59f1891db0eee5b8679bbd654ba8dd7025c73ae00d6125be268f06822a234cfdd4c79d82398cf145833e15440a17133482e9872fd845ab

test:
  secret_key_base: e111ca5bcee57a4d06e57caae6de6b7831290961fbc721c737ffeb120716b40b00ee17bdbef9c95f72a4a86d832206df3952cfcb69cc57cb039cdf3eb03438be

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
